<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ChecksumAlgorithm>SHA1</ChecksumAlgorithm>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.2" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.3.efcore.9.0.0" />
    <PackageReference Include="UAParser" Version="3.1.47" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\front-pages\**" Watch="false" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\repos\NATS\NATS\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\Components\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrowleft.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrowright.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrows.psd" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrow_large_left.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrow_large_right.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrow_left.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrow_left2.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrow_right.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\arrow_right2.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\black50.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\boxed_bgtile.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\bullet.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\bullets.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\bullets.psd" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\bullets2.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\bullet_boxed.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\coloredbg.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\grain.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\gridtile.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\gridtile_3x3.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\gridtile_3x3_white.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\gridtile_white.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\large_left.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\large_right.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\loader.gif" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\loader2.gif" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\navigdots.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\navigdots_bgtile.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\shadow1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\shadow2.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\shadow3.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\small_arrows.psd" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\small_left.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\small_left_boxed.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\small_right.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\small_right_boxed.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\timer.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\timerdot.png" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\transparent.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\white50.png" />
  </ItemGroup>

</Project>
